"""empty message

Revision ID: 46bea005800b
Revises: a451e52f28fb
Create Date: 2020-08-21 21:42:29.709327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46bea005800b'
down_revision = 'a451e52f28fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('moons_number', sa.Integer(), nullable=True))
    op.drop_column('planets', 'moons_numbers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planets', sa.Column('moons_numbers', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('planets', 'moons_number')
    # ### end Alembic commands ###
